openapi: "3.0.2"
info:
  title: API Title
  version: "1.0"
servers:
  - url: http://localhost:8080/v1
paths:
  /authorize:
    description: "authorize based on identity token"
    post:
      tags:
        - "authorize"
      summary: "authorize a session for token"
      description: "authorize based on a centralized token"
      operationId: "authorize"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorizationRequest'
      responses:
        '200':
          description: OK
  /logout/:
    description: "log out of the API session"
    get:
      tags:
        - "logout"
      summary: "de-authorize a session for token"
      description: "de-authorize a session for token"
      operationId: "logout"
      parameters:
        - name: "apiToken"
          in: "query"
          description: "ID of profile to return"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
  /profile:
    description: "add a profile"
    post:
      tags:
        - "profile"
      summary: "create a profile"
      description: "create a profile"
      operationId: "addProfile"
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
      responses:
        '200':
          description: OK
    get:
      tags:
        - "profile"
      summary: "get a profile based on authorized session"
      operationId: "getSessionProfile"
      security:
        - BearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profile"
  /profile/{profileId}:
    description: "profile operations"
    get:
      tags:
        - "profile"
      summary: "get a profile by id"
      description: "get that profile"
      operationId: "getProfile"
      security:
        - BearerAuth: []
      parameters:
        - name: "profileId"
          in: "path"
          description: "ID of profile to return"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profile"
    patch:
      tags:
        - "profile"
      summary: "update attributes of a profile"
      operationId: "patchProfile"
      security:
        - BearerAuth: []
      parameters:
        - name: "profileId"
          in: "path"
          description: "ID of profile to return"
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profile"

  /public/projects:
    description: "published project related calls"
    get:
      tags:
        - "published_project"
      summary: "get published projects"
      operationId: "getPublicProjects"
      security:
        - OptionalBearerAuth: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Project"
  /connections/projects:
    description: "published project related calls"
    get:
      tags:
        - "published_project"
      summary: "get published projects"
      operationId: "getConnectionProjects"
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Project"



  /me/projects:
    description: "project related calls"
    post:
      tags:
        - "project"
      summary: "create a project"
      description: "create a project"
      operationId: "addProject"
      security:
        - BearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '200':
          description: OK
    get:
      tags:
        - "project"
      summary: "get a project based on authorized session"
      operationId: "getSessionProjects"
      security:
        - BearerAuth: [ ]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Project"

  /me/projects/{project_id}/photos:
    description: "add photos to a project"
    post:
      tags:
        - "project_photo"
      summary: "upload a photo to your project."
      description: "upload a photo to your project"
      operationId: "addProjectPhoto"
      security:
        - BearerAuth: [ ]
      parameters:
        - name: "project_id"
          in: "path"
          description: "ID of project to delete"
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fileName:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK

  /me/projects/{project_id}:
    description: "project operations for an individual session"
    delete:
      tags:
        - "project"
      summary: "delete a project by id"
      description: "delete that project"
      operationId: "deleteProject"
      security:
        - BearerAuth: [ ]
      parameters:
        - name: "project_id"
          in: "path"
          description: "ID of project to delete"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
    patch:
      tags:
        - "project"
      summary: "update attributes of a project"
      operationId: "patchProject"
      security:
        - BearerAuth: [ ]
      parameters:
        - name: "project_id"
          in: "path"
          description: "ID of project to patch"
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"


  /projects/{project_id}:
    description: "project operations"
    get:
      tags:
        - "project"
      summary: "get a project by id"
      description: "get that project"
      operationId: "getProject"
      security:
        - BearerAuth: [ ]
      parameters:
        - name: "project_id"
          in: "path"
          description: "ID of project to return"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
  /photos/{photo_id}:
    description: "photo operations"
    get:
      tags:
        - "photo"
      summary: "get a photo"
      operationId: "getPhoto"
      parameters:
        - name: "photo_id"
          in: "path"
          description: "ID of the photo to return"
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
  /photos:
    description: photo post operations
    post:
      tags:
        - "photo"
      summary: "upload a photo"
      description: "upload a photo"
      operationId: "addPhoto"
      security:
        - BearerAuth: [ ]
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                orderId:
                  type: integer
                userId:
                  type: integer
                fileName:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK

components:
  schemas:
    Profile:
      type: object
      properties:
        _id:
          type: "string"
        profile_name:
          type: "string"
        identity_issuer:
          type: "string"
        identity_id:
          type: "string"
        profile_img:
          type: "string"
        connections:
          type: "array"
          items:
            type: "string"
    AuthorizationRequest:
      type: object
      required:
        - identity_token
      properties:
        identity_token:
          type: "string"
    ApiSession:
      type: object
      properties:
        identity_token:
          type: "string"
        identity_issuer:
          type: "string"
        api_token:
          type: "string"
        api_token_expiration:
          type: "integer"
        user_profile:
          type: "string"
    Project:
      type: object
      properties:
        _id:
          type: "string"
        profile_id:
          type: "string"
        summary:
          type: "string"
        description:
          type: "string"
        location:
          type: "string"
        published:
          type: "boolean"
        showcase_photo_id:
          type: "string"
        photo_array:
          type: array
          items:
            type: "string"
        datestmp:
          type: "string"
        share_with:
          type: "string"
          enum:
            - "private"
            - "public"
            - "connections"
        project_days:
          type: array
          items:
            $ref: "#/components/schemas/ProjectDay"

    ProjectDay:
      type: object
      properties:
        id:
          type: "string"
        summary:
          type: "string"
        description:
          type: "string"
        location:
          type: "string"
        datestmp:
          type: "string"
        photos:
          type: "array"
          items:
            type: "string"

    Photo:
      type: object
      properties:
        _id:
          type: "string"
        summary:
          type: "string"
        name:
          type: "string"
        type:
          type: "string"
        data:
          type: "string"
          format: binary

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
    OptionalBearerAuth:
      type: http
      scheme: bearer
security: