openapi: 3.0.2
info:
  title: API Title
  version: "1.0"
servers:
- url: http://localhost:8080/v1
paths:
  /profile:
    description: add a profile
    get:
      tags:
      - profile
      summary: get a profile based on authorized session
      operationId: get_session_profile
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
      security:
      - BearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.profile_controller
  /profile/{profileId}:
    description: profile operations
    get:
      tags:
      - profile
      summary: get a profile by id
      description: get that profile
      operationId: get_profile
      parameters:
      - name: profileId
        in: path
        description: ID of profile to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
      security:
      - BearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.profile_controller
    patch:
      tags:
      - profile
      summary: update attributes of a profile
      operationId: patch_profile
      parameters:
      - name: profileId
        in: path
        description: ID of profile to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Profile'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
      security:
      - BearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.profile_controller
  /me/projects/{project_id}/photos:
    description: add photos to a project
    post:
      tags:
      - project_photo
      summary: upload a photo to your project.
      description: upload a photo to your project
      operationId: add_project_photo
      parameters:
      - name: project_id
        in: path
        description: ID of project to delete
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/project_id_photos_body'
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.project_photo_controller
  /projects/{project_id}/profile:
    description: project public profile
    get:
      tags:
      - project
      summary: get a project owners public profile
      description: get a project owners public profile
      operationId: get_project_profile
      parameters:
      - name: project_id
        in: path
        description: ID of the project to lookup
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicProfile'
      security:
      - BearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.project_controller
  /photos/{photo_id}:
    description: photo operations
    get:
      tags:
      - photo
      summary: get a photo
      operationId: get_photo
      parameters:
      - name: photo_id
        in: path
        description: ID of the photo to return
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
      x-openapi-router-controller: swagger_server.controllers.photo_controller
  /photos:
    description: photo post operations
    post:
      tags:
      - photo
      summary: upload a photo
      description: upload a photo
      operationId: add_photo
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/photos_body'
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      x-openapi-router-controller: swagger_server.controllers.photo_controller
components:
  schemas:
    PublicProfile:
      type: object
      properties:
        profile_name:
          type: string
        profile_img:
          type: string
      example:
        profile_name: profile_name
        profile_img: profile_img
    Profile:
      type: object
      properties:
        _id:
          type: string
        profile_name:
          type: string
        identity_issuer:
          type: string
        identity_id:
          type: string
        profile_img:
          type: string
        connections:
          type: array
          items:
            type: string
      example:
        profile_name: profile_name
        profile_img: profile_img
        identity_id: identity_id
        identity_issuer: identity_issuer
        _id: _id
        connections:
        - connections
        - connections
    Photo:
      type: object
      properties:
        _id:
          type: string
        summary:
          type: string
        name:
          type: string
        type:
          type: string
        data:
          type: string
          format: binary
    project_id_photos_body:
      type: object
      properties:
        fileName:
          type: string
          format: binary
    photos_body:
      type: object
      properties:
        orderId:
          type: integer
        userId:
          type: integer
        fileName:
          type: string
          format: binary
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      x-bearerInfoFunc: swagger_server.controllers.authorization_controller.check_BearerAuth

